create table profiles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, birth_date date not null, cpf varchar(11) not null, email varchar(50), genre varchar(20), name varchar(50) not null, nationality varchar(20), naturalness varchar(30), password varchar(255), user_name varchar(255), primary key (id)) engine=InnoDB;
create table tb_user_profiles (user_id bigint not null, profiles_id bigint not null) engine=InnoDB;
alter table tb_user add constraint UK_TB_USER_CPF unique (cpf);
alter table tb_user_profiles add constraint FKkgmsqf15v6ns18d6es7vuees6 foreign key (profiles_id) references profiles (id);
alter table tb_user_profiles add constraint FK5wdmk99qusbns85aa7a4nv8yt foreign key (user_id) references tb_user (id);
create table profiles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, birth_date date not null, cpf varchar(11) not null, email varchar(50), genre varchar(20), name varchar(50) not null, nationality varchar(20), naturalness varchar(30), password varchar(255), user_name varchar(255), primary key (id)) engine=InnoDB;
create table tb_user_profiles (user_id bigint not null, profiles_id bigint not null) engine=InnoDB;
alter table tb_user add constraint UK_TB_USER_CPF unique (cpf);
alter table tb_user_profiles add constraint FKkgmsqf15v6ns18d6es7vuees6 foreign key (profiles_id) references profiles (id);
alter table tb_user_profiles add constraint FK5wdmk99qusbns85aa7a4nv8yt foreign key (user_id) references tb_user (id);
create table profiles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, birth_date date not null, cpf varchar(11) not null, email varchar(50), genre varchar(20), name varchar(50) not null, nationality varchar(20), naturalness varchar(30), password varchar(255), user_name varchar(255), primary key (id)) engine=InnoDB;
create table tb_user_profiles (user_id bigint not null, profiles_id bigint not null) engine=InnoDB;
alter table tb_user add constraint UK_TB_USER_CPF unique (cpf);
alter table tb_user_profiles add constraint FKkgmsqf15v6ns18d6es7vuees6 foreign key (profiles_id) references profiles (id);
alter table tb_user_profiles add constraint FK5wdmk99qusbns85aa7a4nv8yt foreign key (user_id) references tb_user (id);
create table profiles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, birth_date date not null, cpf varchar(11) not null, email varchar(50), genre varchar(20), name varchar(50) not null, nationality varchar(20), naturalness varchar(30), password varchar(255), user_name varchar(255), primary key (id)) engine=InnoDB;
create table tb_user_profiles (user_id bigint not null, profiles_id bigint not null) engine=InnoDB;
alter table tb_user add constraint UK_TB_USER_CPF unique (cpf);
alter table tb_user_profiles add constraint FKkgmsqf15v6ns18d6es7vuees6 foreign key (profiles_id) references profiles (id);
alter table tb_user_profiles add constraint FK5wdmk99qusbns85aa7a4nv8yt foreign key (user_id) references tb_user (id);
