-- MySQL Script generated by MySQL Workbench
-- Fri Apr  2 20:02:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_USER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `GENRE` VARCHAR(20) NULL,
  `EMAIL` VARCHAR(50) NULL,
  `BIRTH_DATE` DATE NOT NULL,
  `NATURALNESS` VARCHAR(30) NULL,
  `NATIONALITY` VARCHAR(20) NULL,
  `CPF` VARCHAR(11) NOT NULL COMMENT 'mask \'12345678912\'',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UK_TB_USER_CPF` (`CPF` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
